---
title: "Thesis"
author: "Anastasia Stuart"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
  word_document:
    reference_docx: apa_template.docx
    toc: true  # Adds a table of contents
    fig_caption: true  # Enable figure captions
    df_print: kable  # Ensures data frames are printed using kable()
  md_document:
header-includes: \usepackage{setspace}\doublespacing
  \usepackage{indentfirst}
csl: apa.csl
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r child='02_statement.md', eval=TRUE}

```{r child='03_acknowledgements.md', eval=FALSE}

```{r child='04_abstract.md', eval=FALSE}

```{r child='05_table_of_contents.md', eval=TRUE}

```{r child='06_list_of_figures.md', eval=FALSE}

```{r child='07_list_of_tables.md', eval=FALSE}

```{r child='08_abbreviations.md', eval=FALSE}

```{r child='09_introduction.md', eval=TRUE}

```{r child='10_method.md', eval=TRUE}

```{r child='11_results.md', eval=TRUE}

```{r child='12_discussion.md', eval=FALSE}

```{r child='13_references.md', eval=TRUE}

```{r child='16_appendix_1.md', eval=FALSE}


