---
title: "draft"
output: word_document
date: "2024-06-22"
---

```{=tex}
\setcounter{page}{1}
\pagenumbering{arabic}
\doublespacing
\setlength{\parindent}{0.5in}
```
# Introduction

## Problem statement

Insomnia is the most common sleep complaint in Australia [cite], affecting over **how many people** and leading to **health burden** [@sweetman2021]. It is associated with clinical complaints of shortened overnight sleep, difficulty with sleep initiation, and frequent overnight arousals causing clinically significant distress or dysfunction in daily life [@americanpsychiatricassociation2022]. However, there is a clinical population that experience non-restorative sleep (NRS), characterised by poor subjective sleep quality despite objectively normal polysomnographic recordings, leading to impaired daytime functioning [@roth2010]. This population is poorly understood and not clinically managed **explain**. 

The inability to identify objective markers of this **disease** through PSG may result from the inability of current methods to adequately measure sleep. 

**People with NRS and Insomnia may experience subjective and objective sleepiness differently to healthy controls, which impacts their daily life and functioning. This could affect how they need to be managed clinically, and greater understanding of this problem could lead to improved outcomes.**


      ```what is the issue. impact. theoretical model. what is the solution. is there a difference in how NRS and ID percieve daytime tiredness, and is that related to delta power in previous nights sleep?

## Background

- Definition and prevalence of insomnia 
    - [@sweetman_prevalence_2021]
    - [@reynolds2019]
    - Overview of symptoms
    - Models of insomnia 
        - stimulus control model
        - 3P model
    - Insomnia is associated with sleep homeostasis dysfunction, possibly due to decreased homeostatic drive or arousal interfering with the homeostatic process or its dissipation over the night. [@lunsfordavery2021]
        
    - lower sleep duration and lower NREM delta power than HC [@kao2021]
    
- Definition and overview of NRS

Non-restorative sleep is a population experiencing objectively normal sleep as measured by PSG, however a feeling of being unrefreshed upon awakening [@stone2008]. 

    - lower nrem delta power than HC but same objective sleep time [@kao2021]

    - [@stone2008]
      - variation in definition leads to impairment of research

    - Definition and overview of sleep-state misperception
      - What are the neural mechanisms?
      - Why is it important? 
      - How does it affect people
      
      **interweave this in NRS, not actually measuring it in the study so perhaps not necessary to describe?**
      **could be mismeasurement, something to do with how we measure sleep and how we measure sleep is overestimating what we know**
      
      **what are the neural correlates? Is it deficits in delta waves? 
    

      Why are we not able to measure sleep-state misperception? Is it an issue in how we measure sleep?


## Self-reported sleepiness

- subjective sleepiness is a measure of an individual's self-assessed propensity to fall asleep in a particular situation. Persisistent sleepiness is debilitating and often associated with physical or emotional distress

"physiological indices of sleepiness did not occur reliably until subjective perceptions fell between “sleepy” and “extremely sleepy-fighting sleep”; i.e. physiological changes due to sleepiness are not likely to occur until extreme sleepiness is encountered. " [@akerstedt2009]
-  weak association ($$r$$=0.18) between subjective fatigue and sleepiness in individuals with sleep disorders. Analysis of variance testing showed strong association between those patients with prominent fatigue and depressive symptoms (P < 0.01) and illness intrusiveness (P < 0.001). The findings support the notion that subjective fatigue and sleepiness can be independent manifestations of sleep disorders [@hossain2005]
- excessive sleepiness is regarded as one of the cardinal manifestations of sleep disorders and often is accompanied by fatigue, many patients with fatigue complain of insomnia and do not report falling asleep or feeling sleepy at inappropriate times [@hossain2005]

## EEG drowsiness

Drowsiness is the experience of moving from wake to sleep, measured most reliably through EEG. 

- relevance to diagnosis and treatment of sleep disorders

current understanding:

- alpha waves: This brain activity can be easily identified by its topographic distribution (maximum amplitude over occipital regions), frequency range (8–13 Hz), and reactivity (it suffers a dramatic amplitude attenuation with the opening of the eyes). Drowsiness-alpha activity is typically characterized by decreased amplitude over occipital areas, as compared with the wakefulness-alpha rhythm, simultaneous to the appearance of a slower alpha pattern localized over anterior cortical regions.  [@cantero2002]

- detecting fatigue: algorithm (i) $\frac {\theta + \alpha}{\beta}$, algorithm (ii) $\frac {\alpha}{\beta}$, algorithm (iii) $\frac {\theta + \alpha} {\alpha + \beta}$, and algorithm (iv) $\frac {\theta}{\beta}$, were also assessed as possible indicators for fatigue detection. Results showed stable delta and theta activities over time, a slight decrease of alpha activity, and a significant decrease of beta activity (p < 0.05). All four algorithms showed an increase in the ratio of slow wave to fast wave EEG activities over time. Algorithm (i) (θ + α)/β showed a larger increase. [@jap2009]


### Explain brain waves and how they relate to drowsiness
    - AAC
    - Slowing ratio
    
## Power spectra

-  The most common quantitative method employed in sleep studies is spectral analysis, which decomposes a time series of EEG data into power  (squared amplitude) in frequency bins (mV2/bin) , can be expressed as absolute or relative to the summed power in all bins, spectral analysis may represent an objective method for examining the pathophysiological mechanisms underlying insomnia [@zhao2021]
- Raw PSD has a straightforward connection to signal amplitude, with channels expressoinf larger signal amplitudes typically showing larger power, useful when absolute differences in signal amplitude are deemed meaningful (topographical analysis) [@cox2020]
    
## Slow wave sleep

 - EEG slow waves of NREM sleep occur when neurons become bistable and oscillate between two states: a hyperpolarized down-state characterized by neuronal silence (off-period), and a depolarized up-state during which neurons fire (on-period) [@steriade2001]. During up-state, neurons fire at high frequencies typical of waking, and during down state there is a tonic cessation of firing activity in all cortical layers [@steriade1993]
- slow oscillation is a travelling wave that originates at a definite site and travels over the scalp at an estimated speed of 1.2-7.0 m/sec, waves originate more frequently in prefrontal-orbitofrontal regions and propagate in an anteroposterior direction [@massimini2004]. 
 
 - We identified two clusters of delta waves with distinctive properties: (1) a frontal-central cluster characterized by ∼2.5–3.0 Hz, relatively large, notched delta waves (so-called “sawtooth waves”) that tended to occur in bursts, were associated with increased gamma activity and rapid eye movements (EMs), and upon source modeling displayed an occipital-temporal and a frontal-central component and (2) a medial-occipital cluster characterized by more isolated, slower (<2 Hz), and smaller waves that were not associated with rapid EMs, displayed a negative correlation with gamma activity, and were also found in NREM sleep. Therefore, delta waves are an integral part of REM sleep in humans and the two identified subtypes (sawtooth and medial-occipital slow waves) may reflect distinct generation mechanisms and functional roles. [@bernardi2019]
 - Insufficiency of slow-wave sleep may predict cognitive impairment and severity of chronic insomnia [@li2016]

## Delta power

Importance of delta waves in sleep architecture
  - characteristics and function
  - association with restorative sleep processes
  
NRS/ID/HC : quantitative differences in delta power
- best established method of sleep homeostasis - delta power dissipation overnight [@lunsfordavery2021]
- insomnia patients exhibit a slower rate in overnight delta decline compared to HC, not explained by differences in total sleep time or wake after sleep onset. [@lunsfordavery2021]

correlation with daytime drowsiness:

## high frequency arousal

- [@zhao2021] meta-analysis found throughout wakefulness and sleep, patients with ID exhibited increased beta band power, although such increases sometimes extended into neighboring frequency bands, increased theta and gamma power during wake, increased alpha and sigma power during REM, decreased delta and increased theta, alpha, sigma power during NREM sleep. 
- ID is associated with significantly increased EEG activity in high-frequency bands (beta/gamma) during g reststate wakefulness, sleep-onset, non-rapid eye movement, may reflect cortical hyperarousal [@zhao2021]
- no significant differences in waking or NREM sleep power were observed aross all frequency bands in PI [@wu2013]

### Differences of brain waves of people with insomnia/NRS and healthy controls
    - Increased slowing ratio
    - Higher delta and theta power
        - Associated with increased sleepiness and cognitive implications
    - 

## approach
- why are we doing things in the way we are doing? Integrate with theory
    - Link psychological construct to apporach you are using it to measure it
    - Operationalise how you are going to measure constructs
- description of overall research study
  - what type of study it is,   
    - observational, age and sex matched
    

## aim

In order to examine regional differences in brain activity across three populations, we used HD-EEG to measure **spectral power** during resting wake and sleep. We aimed to see if there was a difference in the correlation of objective sleepiness scores to objective measures of drowsiness and if that was associated with topographical cluster differences. Finally, we examined if the regional differences was associated with delta power of previous nights sleep. 
  
## Hypotheses

1. KSS scores will be higher in the ID and NRS groups compared to healthy controls, indicating increased subjective sleepiness. 
2. The correlation between KSS score and Slowing Ratio (SR) will differ significantly between the three groups. Healthy controls will have the strongest relationship between KSS score and SR, while NRS will have the weakest relationship.
3. Topography of channel-by-channel comparisons for normalised power spectral density will reveal electrode cluster differences between the ID and NRS groups and KDT conditions.
4. Clusters associated with higher SR during resting wake will be associated with lower delta power during sleep

## Present study
This study will use HD-EEG to examine brain activity during the KDT to examine the correlation with self-reported sleepiness.
Hypotheses:


## Summary of chapters

\newpage
